const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');const fs=require('node:fs');
function wav(f=369.994,seconds=8){const rate=48000,n=rate*seconds,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(Math.sin(2*Math.PI*f*i/rate)*5000),44+i*2);return b;}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#emptyImport');await page.locator('#files').setInputFiles([{name:'Guitarra Fsharp.wav',mimeType:'audio/wav',buffer:wav()},{name:'Baixo.wav',mimeType:'audio/wav',buffer:wav(110)}]);await page.waitForSelector('#play:not([disabled])');await page.waitForTimeout(500);assert.equal(await page.locator('.strip').count(),3);
await page.locator('#loop').click();await page.locator('#play').click();await page.waitForTimeout(900);assert.match(await page.locator('#play').textContent(),/Pausar/);await page.locator('#menu').click();await page.locator('[data-nav="projects"]').click();assert.match(await page.locator('#play').textContent(),/Pausar/);
await page.locator('#speed').click();await page.locator('[data-preset="80"]').click();await page.locator('#applyDsp').click();await page.waitForTimeout(1600);assert.match(await page.locator('#speed').textContent(),/80%/);assert.match(await page.locator('#play').textContent(),/Pausar/);
await page.locator('#pitch').click();await page.locator('[data-preset="2"]').click();await page.locator('#applyDsp').click();await page.waitForTimeout(1000);await page.screenshot({path:'../verification/web-desktop-0.8.png',fullPage:true});
await page.locator('#play').click();const db=page.locator('[data-fader]').first();await db.fill('700');await page.locator('[data-zero]').first().click();assert.equal(await db.inputValue(),'800');
const downloadPromise=page.waitForEvent('download');await page.locator('#backup').click();const download=await downloadPromise;await download.saveAs('test-results/test.atmytrack');assert.ok(fs.statSync('test-results/test.atmytrack').size>1000);
await page.reload();await page.waitForSelector('#play:not([disabled])');assert.match(await page.locator('#speed').textContent(),/80%/);assert.match(await page.locator('#pitch').textContent(),/\+2/);
await page.locator('#backupFile').setInputFiles('test-results/test.atmytrack');await page.waitForTimeout(700);assert.equal(await page.locator('[data-project]').count(),2);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../verification/web-mobile-0.8.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#menu').click();await page.locator('[data-nav="tuner"]').click();await page.locator('#micStart').click();await page.waitForTimeout(800);assert.match(await page.locator('#micStart').textContent(),/ativo/);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../verification/web-tuner-0.8.png',fullPage:true});await page.locator('#back').click();
const results=await page.evaluate(async()=>{const {Engine}=await import('./engine.js'),{yin,frequency,newProject}=await import('./music.js');const result=[];for(const speed of [100,80,120]){const engine=new Engine(),ctx=await engine.context(),p=newProject('DSP test'),b=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),samples=b.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=.2*Math.sin(2*Math.PI*220*i/ctx.sampleRate);p.tracks=[{id:'one',name:'One',db:0,pan:0,duration:4,speed,pitch:2,route:'master'}];p.loop=true;engine.project=p;engine.buffers.set('one',b);await engine.play();await new Promise(r=>setTimeout(r,1400));const a=ctx.createAnalyser();a.fftSize=8192;engine.master.connect(a);await new Promise(r=>setTimeout(r,200));const data=new Float32Array(8192);a.getFloatTimeDomainData(data);const reading=yin(data,ctx.sampleRate);result.push({speed,frequency:reading.frequency,expected:frequency(59),position:engine.current()});engine.stop();await ctx.close();}return result;});for(const r of results){assert.ok(Math.abs(r.frequency-r.expected)<1,JSON.stringify(r));assert.ok(r.position>.5);}assert.deepEqual(errors,[]);console.log(JSON.stringify({ui:'passed',dsp:results,errors},null,2));fs.writeFileSync('../verification/web-browser-0.8.json',JSON.stringify({ui:'passed',dsp:results,errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
